const edges=[['C1','C2'],['C1','C3'],['C2','C3'],['C2','C4'],['C3','C4'],['C4','C5'],['C5','C6'],['C1','C6']];
const nodes=['C1','C2','C3','C4','C5','C6'];
let k=3,strategy='plain';
const graph=document.getElementById('solverGraph');
const statusEl=document.getElementById('status'),assignEl=document.getElementById('assignments'),backEl=document.getElementById('backtracks'),slotEl=document.getElementById('slots'),bar=document.getElementById('progressBar');
function makeGraph(){graph.innerHTML='';const pos={C1:[18,18],C2:[54,10],C3:[14,55],C4:[55,52],C5:[79,27],C6:[82,75]};for(const n of nodes){const d=document.createElement('div');d.className='sg-node';d.id='sg-'+n;d.textContent=n;d.style.left=pos[n][0]+'%';d.style.top=pos[n][1]+'%';graph.appendChild(d)}edges.forEach(([a,b])=>{const e=document.createElement('div');e.style.position='absolute';e.style.height='1px';e.style.background='rgba(120,240,200,.18)';e.style.transformOrigin='left center';const [ax,ay]=pos[a],[bx,by]=pos[b];const dx=(bx-ax)*2.55,dy=(by-ay)*2.3;const len=Math.sqrt(dx*dx+dy*dy);e.style.width=len+'px';e.style.left=ax+'%';e.style.top=ay+'%';e.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;graph.appendChild(e)})}
function conflict(v,c,assignment){return edges.some(([a,b])=>(a===v&&assignment[b]===c)||(b===v&&assignment[a]===c))}
function solve(){const assignment={},order=strategy==='plain'?[...nodes]:[...nodes].sort((a,b)=>edges.filter(e=>e.includes(b)).length-edges.filter(e=>e.includes(a)).length);let assignments=0,backs=0;function bt(i){if(i===order.length)return true;let v=order[i];let colors=[1,2,3,4].slice(0,k);if(strategy==='pruned')colors=colors.filter(c=>!conflict(v,c,assignment));for(const c of colors){assignments++;document.getElementById('sg-'+v).classList.add('assigned');document.getElementById('sg-'+v).style.boxShadow='0 0 25px rgba(120,240,200,.16)';assignment[v]=c;update(assignments,backs,i+1);if(!conflict(v,c,assignment)&&bt(i+1))return true;delete assignment[v];backs++;document.getElementById('sg-'+v).style.boxShadow='';update(assignments,backs,i)}return false}
const ok=bt(0);return {ok,assignment,assignments,backs,used:new Set(Object.values(assignment)).size}}
function update(a,b,step){assignEl.textContent=a;backEl.textContent=b;bar.style.width=Math.min(100,step/nodes.length*100)+'%'}
function run(){makeGraph();statusEl.textContent='Solving…';assignEl.textContent='0';backEl.textContent='0';slotEl.textContent='—';bar.style.width='0%';setTimeout(()=>{const r=solve();statusEl.textContent=r.ok?'Valid colouring':'No solution';slotEl.textContent=r.ok?r.used:'—';},120)}
document.querySelectorAll('#colorButtons button').forEach(b=>b.onclick=()=>{k=+b.dataset.k;document.querySelectorAll('#colorButtons button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('spaceValue').textContent=`${k}ⁿ`});
document.querySelectorAll('#strategyButtons button').forEach(b=>b.onclick=()=>{strategy=b.dataset.strategy;document.querySelectorAll('#strategyButtons button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.getElementById('runBtn').onclick=run;makeGraph();
